# Site settings
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  publications:
    output: false
  news:
    output: false
  showcase:
    output: false
  posts:
    output: true
